### ISSUE TITLE
克隆下来的hugging仓库数据只有7M，没有18g

### ISSUE THREAD

**Issue by Samge0** [soulteary/docker-stable-diffusion-taiyi#1]
执行：
git clone https://huggingface.co/IDEA-CCNL/Taiyi-Stable-Diffusion-1B-Chinese-v0.1

![Termius_-_192_168_5_116-2](https://user-images.githubusercontent.com/17336101/207499279-3b3d03fa-2fc0-4088-a74e-b149d845b410.png)

**Comment by soulteary** [comment]
1. 检查是否真的 clone 完毕
2. 检查系统中 git 版本或参考 GitHub 官方文档，确认 git-lfs 正常
3. 再次 git clone
