### ISSUE TITLE
windows11 wsl2 docker环境下docker-compose失败

### ISSUE THREAD

**Issue by wk224** [soulteary/docker-stable-diffusion-taiyi#2]
运行docker-compose失败，
home:~/data/taiyi$ docker-compose up -d
[+] Running 0/0
 ⠋ Container taiyi  Creating                                                                                       0.0s
Error response from daemon: Unknown runtime specified nvidia
home:~/data/taiyi$

目前win11的wsl貌似是支持gpu ml和加速的，运行nvidia-smi有显示gpu信息
home:~$ nvidia-smi
Sat Dec 17 20:07:21 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.65       Driver Version: 527.56       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0  On |                  N/A |
| 17%   29C    P8     6W / 175W |   2925MiB /  8192MiB |     10%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

**Comment by wk224** [comment]
已解决，docker-compose.yml按照 https://docs.docker.com/compose/gpu-support/ 里面修改，已正常运行

**Comment by waynehong** [comment]
> 已解决，docker-compose.yml按照 https://docs.docker.com/compose/gpu-support/ 里面修改，已正常运行

遇到一样的问题，可以发下修改后的文件吗

**Comment by wk224** [comment]
> 
我是把yml文件里的 runtime: nvidia 替换为
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

其他都是一样，你可以试试
