### ISSUE TITLE
help

### ISSUE THREAD

**Issue by mindcodings** [soulteary/docker-stable-diffusion-taiyi#4]
请问如何载入其他的模型
https://civitai.com/models/4201/realistic-vision-v13
就像这个模型  我在docker-compose.yml里
```
volumes:
- ./Taiyi-Stable-Diffusion-1B-Chinese-v0.1:/stable-diffusion-webui/models/Taiyi-Stable-Diffusion-1B-Chinese-v0.1
- ./Realistic_Vision_V1.3:/stable-diffusion-webui/models/Realistic_Vision_V1.3
```
但是webui还是没有生效

**Comment by soulteary** [comment]
1. 这个项目只针对 taiyi。
2. C站模型复现最简单的方法是用 https://github.com/AUTOMATIC1111/stable-diffusion-webui
